import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Navbar from "../components/Navbar";
import { motion } from "framer-motion";
import ScrollToTop from "../components/ScrollToTop";
import Hero from "../components/Hero";
import ServicesSection from "../components/ServicesSection";
import AboutSection from "../components/AboutSection";
import Photos from "../components/Photos";
import TestimonialSection from "../components/TestimonialSection";
import ContactSection from "../components/ContactSection";

export default function Home() {
  return (
    <div className={styles.background}>
      <div className={styles.container} id='container'>
        <Head>
          <title>Create Next App</title>
          <meta name='description' content='Generated by create next app' />
          <link rel='icon' href='/favicon.ico' />
        </Head>

        <motion.main className={styles.main} initial='hidden' animate='show'>
          <ScrollToTop />
          <Navbar />
          <Hero />
          <ServicesSection />
          <AboutSection />
          <Photos />
          <TestimonialSection />
          <ContactSection />
        </motion.main>
      </div>
    </div>
  );
}
